// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzfoqjcfksrcplprcbno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6Zm9xamNma3NyY3BscHJjYm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mzg2OTIsImV4cCI6MjA2NTUxNDY5Mn0.X3W7UoJoaE6h1OhORKCfjfwwZ25kWp7DkjLLBGtUNG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);