// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykxphjcbfewhqcunohqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlreHBoamNiZmV3aHFjdW5vaHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MTEwNzIsImV4cCI6MjA3NzM4NzA3Mn0.wVHnwmSHn_Tx655jNqp7ixw_lBZ8vRErPCq7zLkk2VM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});